{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul.fullname" . }}-controller-metrics
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: controller
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: controller
{{- end }}
