{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-controller-metrics-reader
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: controller
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
